Misc:
  kick: true
  no_permission: "&cYou do not have permission to run this command."
  config_reloaded: "&aSuccessfully reloaded the config file"
PacketLimiter: # Global
  enabled: false
  check-interval: 20 # Time in ticks
  max-rate: 300 # Time in ticks
  kick-message: "§8[§dServerPatches§8] §fPassed packet limit of §e${max}"
ClickEventExploit: #1.17.x & Below
  enabled: false
  kick-message: "§8[§dServerPatches§8] §fInternal Exception: Invalid Packet Recieved"
LecternExploit:
  enabled: false
  kick-message: "§8[§dServerPatches§8] §fInternal Exception: Invalid Packet Recieved"
ClickSwapExploit: #?.? - 1.20.2
  enabled: true
  kick-message: "§8[§dServerPatches§8] §fInternal Exception: Invalid Packet Recieved"
DataCommandFilter: #?.? - 1.20.4
  enabled: true
  kick-message: "§8[§dServerPatches§8] §fInternal Exception: Invalid Packet Recieved"

#SimplePhysics:
#  enabled: true