PacketLimiter: #Global
  enabled: true
  check-interval: 60 #Time in ticks
  max-rate: 300
  kick-message: "§8[§dProtection§8] §fPassed packet limit of §e${max}"
ClickEventExploit: #1.17.x & Below
  enabled: true
  kick-message: "§8[§dProtection§8] Internal Exception: Invalid Packet Recieved"
LecternExploit:
  enabled: true
  kick-message: "§8[§dProtection§8] Internal Exception: Invalid Packet Recieved"
#SimplePhysics:
#  enabled: true