config-version: 1
Misc:
  kick: true
  no_permission: "&cYou do not have permission to run this command."
  config_reloaded: "&aSuccessfully reloaded the config file"
ClickEventExploit:
  enabled: false
  kick-message: "§8[§dServerPatches§8] §fFailed packet filter - ClickEventExploit"
LecternExploit:
  enabled: false
  kick-message: "§8[§dServerPatches§8] §fFailed packet filter - LecternExploit"
ClickSwapExploit:
  enabled: true
  kick-message: "§8[§dServerPatches§8] §fFailed packet filter - ClickSwapExploit"
DataCommandFilter:
  enabled: true
  kick-message: "§8[§dServerPatches§8] §fFailed packet filter - DataCommandFilter"