name: ServerPatches
api-version: 1.17
main: rs.jamie.serverpatches.Main
version: '${version}'
authors: [Summiner]

# Required for PacketEvents
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot

commands:
  spatches:
    description: Adds the ability to reload ServerPatches config options, maybe more in the future
    usage: /spatches reload